name: update

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: DeterminateSystems/nix-installer-action@v1
    - uses: DeterminateSystems/update-flake-lock@v19
      with:
        sign-commits: true
        git-author-name: 'Mecha Sorceress'
        git-author-email: 'infinitivewitch+bot@disroot.org'
        git-committer-name: 'Mecha Sorceress'
        git-committer-email: 'infinitivewitch+bot@disroot.org'
        pr-assignees: infinitivewitch
        pr-title: 'ci: update flake.lock'
        commit-msg: 'ci: update flake.lock'
        token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
        gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        pr-labels: |
          :muscle: Effort: 1
          :wrench: Type: Maintenance
          :low_brightness: Priority: Low
          :construction: Status: In Progress
  nvfetcher:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3.3.1
      with:
        path: ~/.local/share/nvfetcher
        key: ${{ runner.os }}-nvfetcher
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix develop --command , pkg
    - run: nix develop --command , fmt
    - uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
        add-paths: |
          scrolls/packages/pkgs/_sources/generated.*
        title: 'ci: update nvfetcher sources'
        body: |
          # Update Report

          > Auto-generated by [create-pull-request][1]
          
          - updated generated.json and generated.nix following nvfetcher.toml

          [1]: https://github.com/peter-evans/create-pull-request
        commit-message: 'ci: update nvfetcher sources'
        committer: 'Mecha Sorceress <infinitivewitch+bot@disroot.org>'
        author: 'Mecha Sorceress <infinitivewitch+bot@disroot.org>'
        branch: update_nvfetcher_sources_action
        delete-branch: true
        labels: |
          :muscle: Effort: 1
          :wrench: Type: Maintenance
          :low_brightness: Priority: Low
          :construction: Status: In Progress
        assignees: infinitivewitch
        