name: update-pkgs

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  nvfetcher:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3.3.1
      with:
        path: |
          ~/.local/share/nvfetcher/.shake.database
        key: ${{ hashFiles('scrolls/packages/pkgs/_sources/nvfetcher.toml') }}-${{ hashFiles('scrolls/packages/pkgs/_sources/generated.nix') }}
        restore-keys: |
          ${{ hashFiles('scrolls/packages/pkgs/_sources/nvfetcher.toml') }}-
    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix develop --command , pkg
    - run: nix develop --command , fmt
    - uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
        add-paths: |
          scrolls/packages/pkgs/_sources/generated.*
        title: 'ci: update nvfetcher sources'
        body: |
          # Update Report

          > Auto-generated by [create-pull-request][1]
          
          - updated generated.json and generated.nix following nvfetcher.toml

          [1]: https://github.com/peter-evans/create-pull-request
        commit-message: 'ci: update nvfetcher sources'
        committer: 'Mecha Sorceress <infinitivewitch+bot@disroot.org>'
        author: 'Mecha Sorceress <infinitivewitch+bot@disroot.org>'
        branch: update_nvfetcher_sources_action
        delete-branch: true
        labels: |
          :muscle: Effort: 1
          :wrench: Type: Maintenance
          :low_brightness: Priority: Low
          :construction: Status: In Progress
        assignees: infinitivewitch